### ISSUE TITLE
Question on ESPPRC.preprocess

### ISSUE THREAD

**Issue by dymodi** [ToonWeyens/pylgrim#3]
Hi, on the project page: https://pypi.org/project/pylgrim/ the API is listed as

`best_path, best_path_label = GSSA(G, source, target, max_res, res_min, res_name='res_cost')`

and 

`G_pre, res_min = ESPPRC.preprocess(G, source, target, max_res, res_name='res_cost')`

First I thought the `G` should be passed into `GSSA` but not `G_pre`. But this leads to very confusing errors. Then I found `G_pre` should be passed into `GSSA`. 

I just want to make sure my guess and wonder if there is a way to avoid this confusion on the project page.

Thanks

**Comment by ToonWeyens** [comment]
Hi @dymodi , that's a valid remark. Thanks!

I did state it somewhere, but indeed, it should be more clear!

**Comment by ToonWeyens** [comment]
I made a change in the documentation and will push a new version some time soon!

**Comment by ToonWeyens** [comment]
If you clone the newest newest commit from git (b099ad0474d10fede07f5cea480695c88cb3f07e) through

    git clone https://github.com/ToonWeyens/pylgrim.git

this should be fixed.
