### ISSUE TITLE
Question about ESPP.py

### ISSUE THREAD

**Issue by torressa** [ToonWeyens/pylgrim#5]
Hi Toon,

Thanks for the module!
I think i found a minor bug, but just to be sure:
In the `DLA` function in the `ESPP.py` file, line 222, should `G.nodes` be `G.nodes()`?
I keep getting an `instancemethod` error when I try to run your `test_ESPP.py` file.

Best,
David

**Comment by ToonWeyens** [comment]
Thanks! I fixed it!
